const days=[
{n:'01',date:'10月03日 · 周六',title:'抵达曼谷',items:[['07:30','PVG → BKK 11:05','Suvarnabhumi Airport'],['12:00','携程舒适型接机','Suvarnabhumi Airport'],['13:30','Pullman 办理入住','Pullman Bangkok King Power'],['15:30','King Power Rangnam','King Power Rangnam'],['17:00','Victory Monument','Victory Monument Bangkok'],['19:00','Asiatique 夜景','Asiatique The Riverfront']]},
{n:'02',date:'10月04日 · 周日',title:'曼谷文化日',items:[['上午','Khlong Bang Luang 水上市场','Khlong Bang Luang Floating Market'],['下午','大皇宫','The Grand Palace Bangkok'],['下午','卧佛寺 Wat Pho','Wat Pho Bangkok'],['傍晚','郑王庙 Wat Arun','Wat Arun Bangkok'],['晚上','朱拉隆功夜市','Chulalongkorn University Night Market']]},
{n:'03',date:'10月05日 · 周一',title:'换酒店与购物',items:[['上午','Pullman 退房','Pullman Bangkok King Power'],['中午','Renaissance 入住','Renaissance Bangkok Ratchaprasong'],['下午','CentralWorld','CentralWorld Bangkok'],['下午','Siam Paragon','Siam Paragon'],['傍晚','Big C','Big C Supercenter Ratchadamri'],['晚上','四面佛 Erawan Shrine','Erawan Shrine']]},
{n:'04',date:'10月06日 · 周二',title:'城市体验',items:[['上午','ICONSIAM','ICONSIAM'],['下午','湄南河景体验','Chao Phraya River Bangkok'],['晚上','高级泰餐','Thai Fine Dining Bangkok']]},
{n:'05',date:'10月07日 · 周三',title:'放松日',items:[['上午','VIE Hotel Suite 体验','VIE Hotel Bangkok MGallery'],['下午','MBK','MBK Center'],['下午','Siam Center','Siam Center'],['晚上','最后一顿泰餐','Thai Restaurant Siam Bangkok']]},
{n:'06',date:'10月08日 · 周四',title:'返回上海',items:[['上午','酒店早餐','VIE Hotel Bangkok MGallery'],['中午','前往机场','Suvarnabhumi Airport'],['起飞','曼谷 → 上海','Suvarnabhumi Airport']]}
];
const daysEl=document.querySelector('#days');
const appleMapLink=q=>`https://maps.apple.com/?q=${encodeURIComponent(q)}`;
const googleMapLink=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const grabLink=q=>`https://grab.onelink.me/2695613898?af_dp=grab%3A%2F%2Fopen%3FscreenType%3DBOOKING%26dropOffLocationName%3D${encodeURIComponent(q)}`;
daysEl.innerHTML=days.map((d,i)=>`<article class="day" data-day="${i}"><div class="day-head"><span class="day-num">${d.n}</span><span class="day-date">${d.date}</span></div><h3>${d.title}</h3><ul class="timeline">${d.items.map(x=>`<li><time>${x[0]}</time><span>${x[1]}</span><span class="place-links"><a class="apple-map" href="${appleMapLink(x[2])}" target="_blank" rel="noopener" aria-label="在 Apple Maps 查看 ${x[1]}">Apple</a><a href="${googleMapLink(x[2])}" target="_blank" rel="noopener" aria-label="在 Google Maps 查看 ${x[1]}">Google</a><a href="${grabLink(x[2])}" target="_blank" rel="noopener" aria-label="使用 Grab 前往 ${x[1]}">Grab</a></span></li>`).join('')}</ul><label class="complete"><input type="checkbox" data-check="${i}"><span>完成今日行程</span></label></article>`).join('');
const checks=[...document.querySelectorAll('[data-check]')];
function update(){let done=0;checks.forEach((c,i)=>{const yes=localStorage.getItem(`bkk-day-${i}`)==='1';c.checked=yes;c.closest('.day').classList.toggle('done',yes);if(yes)done++});document.querySelector('#progressText').textContent=`${done} / 6`;document.querySelector('#progressBar').style.width=`${done/6*100}%`}
checks.forEach((c,i)=>c.addEventListener('change',()=>{localStorage.setItem(`bkk-day-${i}`,c.checked?'1':'0');update()}));update();
const links=[...document.querySelectorAll('.topbar nav a')];const sections=links.map(a=>document.querySelector(a.getAttribute('href')));new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}})},{rootMargin:'-30% 0px -60% 0px'}).observe(sections[0]);sections.slice(1).forEach(s=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${s.id}`))}),{rootMargin:'-30% 0px -60% 0px'}).observe(s));
document.querySelector('#shareBtn').addEventListener('click',async()=>{const data={title:'2026 Bangkok Trip Planner',text:'我的曼谷六天五晚旅行计划'};if(navigator.share){try{await navigator.share(data)}catch(e){}}else{location.hash='schedule'}});
if ('serviceWorker' in navigator && location.protocol.startsWith('http')) {
  window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js'));
}
